### ISSUE TITLE
Start groups cli command

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-iam-support#2]
Create a command for viewing groups:
```
ucdlib-iam groups list|ls
```

which queries the pg database and displays all groups. I started a class here: 
https://github.com/UCDavisLibrary/ucdlib-iam-support/blob/main/lib/src/utils/groups.js

make options for filtering by
- active/archive
- parent group
- group type
- part of org

Before you start, make sure to:
- pull most recent code
- build-local-dev
- generate-deployment-files
- docker compose down -v

**Comment by sbagg** [comment]
Issue #3
